config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'top#index'
  resources :menus, :except => [:edit, :update]
  resources :comments, :except => [:index, :edit, :update, :show]

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :menu
  belongs_to :user
end

app/models/menu.rb
class Menu < ActiveRecord::Base
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :menus
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
  end

  def create
  end

  def destroy
  end

end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :set_menu, :only => [:show, :destroy]
  def index
    @menus = Menu.all
  end

  def new
    @menu = Menu.new
  end

  def create
    @menu = Menu.new(menu_params)
    if @menu.save
      redirect_to root_path
    else
      render action: "new"
    end
  end

  def show
  end

  def destroy
    @menu.destroy
    redirect_to root_path
  end

  private
    def set_menu
      @menu = Menu.find(params[:id])
    end

    def menu_params
      params.require(:menu).permit(:content,:media)
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    @menus = Menu.all
    @comments = Comment.all
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>maccho</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/menus/new.html.erb
<h1>views/menus/new</h1>
<%= form_for (@menu) do |f| %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.submit "Send" %>
<% end %>
<%= link_to "Top", root_path %>

app/views/menus/show.html.erb
<h1>views/menus/show</h1>
<%= @menu.content %>
<br>
<%= link_to "Delete", menu_path(@menu), method: :delete %>
<%= link_to "Top", root_path %>

app/views/top/index.html.erb
<h1>views/top/index</h1>

<h3><%= notice %></h3>

<% if user_signed_in? %>
  <%= link_to "Mypage", edit_user_registration_path %>
  <%= link_to "Log out", destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to "Log in", new_user_session_path %>
  <%= link_to "Sign up", new_user_registration_path %>
<% end %>
<br>

<%= link_to "New", new_menu_path %>
<br>

<% @menus.each do |menu| %>
  <%= menu.content %>
  <br>
  <%= link_to "Show", menu_path(menu) %>
  <%= link_to "Delete", menu_path(menu), method: :delete %>
  <br>
<% end %>